# Generated by Django 5.1.4 on 2025-01-16 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
